/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) s622arm_nmpc_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {33, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {19, 1, 1};
static const casadi_int casadi_s6[203] = 
  {19, 19, 0, 12, 24, 36, 48, 60,
  72, 73, 79, 85, 91, 97, 103, 109,
  121, 133, 145, 157, 169, 181, 0, 1,
  2, 3, 4, 5, 13, 14, 15, 16,
  17, 18, 0, 1, 2, 3, 4, 5,
  13, 14, 15, 16, 17, 18, 0, 1,
  2, 3, 4, 5, 13, 14, 15, 16,
  17, 18, 0, 1, 2, 3, 4, 5,
  13, 14, 15, 16, 17, 18, 0, 1,
  2, 3, 4, 5, 13, 14, 15, 16,
  17, 18, 0, 1, 2, 3, 4, 5,
  13, 14, 15, 16, 17, 18, 6, 7,
  8, 9, 10, 11, 12, 7, 8, 9,
  10, 11, 12, 7, 8, 9, 10, 11,
  12, 7, 8, 9, 10, 11, 12, 7,
  8, 9, 10, 11, 12, 7, 8, 9,
  10, 11, 12, 0, 1, 2, 3, 4,
  5, 13, 14, 15, 16, 17, 18, 0,
  1, 2, 3, 4, 5, 13, 14, 15,
  16, 17, 18, 0, 1, 2, 3, 4,
  5, 13, 14, 15, 16, 17, 18, 0,
  1, 2, 3, 4, 5, 13, 14, 15,
  16, 17, 18, 0, 1, 2, 3, 4,
  5, 13, 14, 15, 16, 17, 18, 0,
  1, 2, 3, 4, 5, 13, 14, 15,
  16, 17, 18};
static const casadi_int casadi_s7[3] = {0, 0, 1};
static const casadi_int casadi_s8[3] = {0, 19, 1};

/* s622arm_nmpc_cost_ext_cost_fun_jac_hess:(i0[12],i1[7],i2[0],i3[33])->(o0,o1[19],o2[19x19,181nz],o3[],o4[0x19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72, a73, a74, a75, a76, a77, a78, a79, a80, a81, a82, a83;
  casadi_real a84, a85, a86, a87, a88;
  a00=arg[3]? arg[3][12] : 0;
  a01=4.;
  a02=5.0000000000000000e-01;
  a03=arg[0]? arg[0][0] : 0;
  a04=arg[3]? arg[3][0] : 0;
  a03=(a03-a04);
  a04=(a02*a03);
  a05=sin(a04);
  a06=casadi_sq(a05);
  a07=arg[0]? arg[0][1] : 0;
  a08=arg[3]? arg[3][1] : 0;
  a07=(a07-a08);
  a08=(a02*a07);
  a09=sin(a08);
  a10=casadi_sq(a09);
  a06=(a06+a10);
  a10=arg[0]? arg[0][2] : 0;
  a11=arg[3]? arg[3][2] : 0;
  a10=(a10-a11);
  a11=(a02*a10);
  a12=sin(a11);
  a13=casadi_sq(a12);
  a06=(a06+a13);
  a13=arg[0]? arg[0][3] : 0;
  a14=arg[3]? arg[3][3] : 0;
  a13=(a13-a14);
  a14=(a02*a13);
  a15=sin(a14);
  a16=casadi_sq(a15);
  a06=(a06+a16);
  a16=arg[0]? arg[0][4] : 0;
  a17=arg[3]? arg[3][4] : 0;
  a16=(a16-a17);
  a17=(a02*a16);
  a18=sin(a17);
  a19=casadi_sq(a18);
  a06=(a06+a19);
  a19=arg[0]? arg[0][5] : 0;
  a20=arg[3]? arg[3][5] : 0;
  a19=(a19-a20);
  a20=(a02*a19);
  a21=sin(a20);
  a22=casadi_sq(a21);
  a06=(a06+a22);
  a06=(a01*a06);
  a06=(a00*a06);
  a22=arg[3]? arg[3][13] : 0;
  a23=arg[0]? arg[0][6] : 0;
  a24=arg[3]? arg[3][6] : 0;
  a24=(a23-a24);
  a25=casadi_sq(a24);
  a26=arg[0]? arg[0][7] : 0;
  a27=arg[3]? arg[3][7] : 0;
  a27=(a26-a27);
  a28=casadi_sq(a27);
  a25=(a25+a28);
  a28=arg[0]? arg[0][8] : 0;
  a29=arg[3]? arg[3][8] : 0;
  a29=(a28-a29);
  a30=casadi_sq(a29);
  a25=(a25+a30);
  a30=arg[0]? arg[0][9] : 0;
  a31=arg[3]? arg[3][9] : 0;
  a31=(a30-a31);
  a32=casadi_sq(a31);
  a25=(a25+a32);
  a32=arg[0]? arg[0][10] : 0;
  a33=arg[3]? arg[3][10] : 0;
  a33=(a32-a33);
  a34=casadi_sq(a33);
  a25=(a25+a34);
  a34=arg[0]? arg[0][11] : 0;
  a35=arg[3]? arg[3][11] : 0;
  a35=(a34-a35);
  a36=casadi_sq(a35);
  a25=(a25+a36);
  a25=(a22*a25);
  a06=(a06+a25);
  a25=arg[3]? arg[3][14] : 0;
  a36=arg[1]? arg[1][0] : 0;
  a37=casadi_sq(a36);
  a38=arg[1]? arg[1][1] : 0;
  a39=casadi_sq(a38);
  a37=(a37+a39);
  a39=arg[1]? arg[1][2] : 0;
  a40=casadi_sq(a39);
  a37=(a37+a40);
  a40=arg[1]? arg[1][3] : 0;
  a41=casadi_sq(a40);
  a37=(a37+a41);
  a41=arg[1]? arg[1][4] : 0;
  a42=casadi_sq(a41);
  a37=(a37+a42);
  a42=arg[1]? arg[1][5] : 0;
  a43=casadi_sq(a42);
  a37=(a37+a43);
  a37=(a25*a37);
  a06=(a06+a37);
  a37=arg[3]? arg[3][22] : 0;
  a43=arg[3]? arg[3][21] : 0;
  a44=arg[3]? arg[3][15] : 0;
  a03=(a44*a03);
  a45=arg[3]? arg[3][16] : 0;
  a07=(a45*a07);
  a03=(a03+a07);
  a07=arg[3]? arg[3][17] : 0;
  a10=(a07*a10);
  a03=(a03+a10);
  a10=arg[3]? arg[3][18] : 0;
  a13=(a10*a13);
  a03=(a03+a13);
  a13=arg[3]? arg[3][19] : 0;
  a16=(a13*a16);
  a03=(a03+a16);
  a16=arg[3]? arg[3][20] : 0;
  a19=(a16*a19);
  a03=(a03+a19);
  a43=(a43+a03);
  a03=casadi_sq(a43);
  a19=9.9999999999999995e-07;
  a03=(a03+a19);
  a03=sqrt(a03);
  a46=(a43+a03);
  a47=(a02*a46);
  a47=casadi_sq(a47);
  a47=(a37*a47);
  a06=(a06+a47);
  a47=arg[3]? arg[3][31] : 0;
  a48=arg[3]? arg[3][29] : 0;
  a49=2.0000000000000000e-02;
  a50=arg[3]? arg[3][23] : 0;
  a23=(a50*a23);
  a51=arg[3]? arg[3][24] : 0;
  a26=(a51*a26);
  a23=(a23+a26);
  a26=arg[3]? arg[3][25] : 0;
  a28=(a26*a28);
  a23=(a23+a28);
  a28=arg[3]? arg[3][26] : 0;
  a30=(a28*a30);
  a23=(a23+a30);
  a30=arg[3]? arg[3][27] : 0;
  a32=(a30*a32);
  a23=(a23+a32);
  a32=arg[3]? arg[3][28] : 0;
  a34=(a32*a34);
  a23=(a23+a34);
  a34=arg[3]? arg[3][30] : 0;
  a23=(a23+a34);
  a23=(a49*a23);
  a48=(a48+a23);
  a23=2.0000000000000001e-04;
  a34=(a50*a36);
  a52=(a51*a38);
  a34=(a34+a52);
  a52=(a26*a39);
  a34=(a34+a52);
  a52=(a28*a40);
  a34=(a34+a52);
  a52=(a30*a41);
  a34=(a34+a52);
  a52=(a32*a42);
  a34=(a34+a52);
  a34=(a23*a34);
  a48=(a48+a34);
  a34=casadi_sq(a48);
  a34=(a34+a19);
  a34=sqrt(a34);
  a19=(a34-a48);
  a52=(a02*a19);
  a52=casadi_sq(a52);
  a52=(a47*a52);
  a06=(a06+a52);
  a52=arg[1]? arg[1][6] : 0;
  a53=casadi_sq(a52);
  a53=(a47*a53);
  a06=(a06+a53);
  if (res[0]!=0) res[0][0]=a06;
  a48=(a48+a48);
  a19=(a19*a47);
  a19=(a02*a19);
  a34=(a34+a34);
  a06=(a19/a34);
  a53=(a48*a06);
  a53=(a53-a19);
  a19=(a23*a53);
  a54=(a50*a19);
  a36=(a36+a36);
  a36=(a36*a25);
  a54=(a54+a36);
  if (res[1]!=0) res[1][0]=a54;
  a54=(a51*a19);
  a38=(a38+a38);
  a38=(a38*a25);
  a54=(a54+a38);
  if (res[1]!=0) res[1][1]=a54;
  a54=(a26*a19);
  a39=(a39+a39);
  a39=(a39*a25);
  a54=(a54+a39);
  if (res[1]!=0) res[1][2]=a54;
  a54=(a28*a19);
  a40=(a40+a40);
  a40=(a40*a25);
  a54=(a54+a40);
  if (res[1]!=0) res[1][3]=a54;
  a54=(a30*a19);
  a41=(a41+a41);
  a41=(a41*a25);
  a54=(a54+a41);
  if (res[1]!=0) res[1][4]=a54;
  a19=(a32*a19);
  a42=(a42+a42);
  a42=(a42*a25);
  a19=(a19+a42);
  if (res[1]!=0) res[1][5]=a19;
  a52=(a52+a52);
  a52=(a52*a47);
  if (res[1]!=0) res[1][6]=a52;
  a46=(a46*a37);
  a46=(a02*a46);
  a43=(a43+a43);
  a03=(a03+a03);
  a52=(a46/a03);
  a19=(a43*a52);
  a46=(a46+a19);
  a19=(a44*a46);
  a04=cos(a04);
  a01=(a01*a00);
  a00=(a05*a01);
  a42=(a04*a00);
  a42=(a02*a42);
  a19=(a19+a42);
  a19=(a19+a42);
  if (res[1]!=0) res[1][7]=a19;
  a19=(a45*a46);
  a08=cos(a08);
  a42=(a09*a01);
  a54=(a08*a42);
  a54=(a02*a54);
  a19=(a19+a54);
  a19=(a19+a54);
  if (res[1]!=0) res[1][8]=a19;
  a19=(a07*a46);
  a11=cos(a11);
  a54=(a12*a01);
  a41=(a11*a54);
  a41=(a02*a41);
  a19=(a19+a41);
  a19=(a19+a41);
  if (res[1]!=0) res[1][9]=a19;
  a19=(a10*a46);
  a14=cos(a14);
  a41=(a15*a01);
  a40=(a14*a41);
  a40=(a02*a40);
  a19=(a19+a40);
  a19=(a19+a40);
  if (res[1]!=0) res[1][10]=a19;
  a19=(a13*a46);
  a17=cos(a17);
  a40=(a18*a01);
  a39=(a17*a40);
  a39=(a02*a39);
  a19=(a19+a39);
  a19=(a19+a39);
  if (res[1]!=0) res[1][11]=a19;
  a46=(a16*a46);
  a20=cos(a20);
  a19=(a21*a01);
  a39=(a20*a19);
  a39=(a02*a39);
  a46=(a46+a39);
  a46=(a46+a39);
  if (res[1]!=0) res[1][12]=a46;
  a53=(a49*a53);
  a46=(a50*a53);
  a24=(a24+a24);
  a24=(a24*a22);
  a46=(a46+a24);
  if (res[1]!=0) res[1][13]=a46;
  a46=(a51*a53);
  a27=(a27+a27);
  a27=(a27*a22);
  a46=(a46+a27);
  if (res[1]!=0) res[1][14]=a46;
  a46=(a26*a53);
  a29=(a29+a29);
  a29=(a29*a22);
  a46=(a46+a29);
  if (res[1]!=0) res[1][15]=a46;
  a46=(a28*a53);
  a31=(a31+a31);
  a31=(a31*a22);
  a46=(a46+a31);
  if (res[1]!=0) res[1][16]=a46;
  a46=(a30*a53);
  a33=(a33+a33);
  a33=(a33*a22);
  a46=(a46+a33);
  if (res[1]!=0) res[1][17]=a46;
  a53=(a32*a53);
  a35=(a35+a35);
  a35=(a35*a22);
  a53=(a53+a35);
  if (res[1]!=0) res[1][18]=a53;
  a53=(a23*a50);
  a35=(a53+a53);
  a35=(a06*a35);
  a46=(a48*a53);
  a46=(a46/a34);
  a53=(a46-a53);
  a53=(a47*a53);
  a53=(a02*a53);
  a33=(a53/a34);
  a31=(a06/a34);
  a46=(a46+a46);
  a46=(a31*a46);
  a33=(a33-a46);
  a33=(a48*a33);
  a35=(a35+a33);
  a35=(a35-a53);
  a35=(a23*a35);
  a35=(a50*a35);
  a53=2.;
  a25=(a53*a25);
  a35=(a35+a25);
  if (res[2]!=0) res[2][0]=a35;
  a35=(a23*a51);
  a33=(a35+a35);
  a33=(a06*a33);
  a46=(a48*a35);
  a46=(a46/a34);
  a35=(a46-a35);
  a35=(a47*a35);
  a35=(a02*a35);
  a29=(a35/a34);
  a46=(a46+a46);
  a46=(a31*a46);
  a29=(a29-a46);
  a29=(a48*a29);
  a33=(a33+a29);
  a33=(a33-a35);
  a33=(a23*a33);
  a35=(a50*a33);
  if (res[2]!=0) res[2][1]=a35;
  a29=(a23*a26);
  a46=(a29+a29);
  a46=(a06*a46);
  a27=(a48*a29);
  a27=(a27/a34);
  a29=(a27-a29);
  a29=(a47*a29);
  a29=(a02*a29);
  a24=(a29/a34);
  a27=(a27+a27);
  a27=(a31*a27);
  a24=(a24-a27);
  a24=(a48*a24);
  a46=(a46+a24);
  a46=(a46-a29);
  a46=(a23*a46);
  a29=(a50*a46);
  if (res[2]!=0) res[2][2]=a29;
  a24=(a23*a28);
  a27=(a24+a24);
  a27=(a06*a27);
  a39=(a48*a24);
  a39=(a39/a34);
  a24=(a39-a24);
  a24=(a47*a24);
  a24=(a02*a24);
  a38=(a24/a34);
  a39=(a39+a39);
  a39=(a31*a39);
  a38=(a38-a39);
  a38=(a48*a38);
  a27=(a27+a38);
  a27=(a27-a24);
  a27=(a23*a27);
  a24=(a50*a27);
  if (res[2]!=0) res[2][3]=a24;
  a38=(a23*a30);
  a39=(a38+a38);
  a39=(a06*a39);
  a36=(a48*a38);
  a36=(a36/a34);
  a38=(a36-a38);
  a38=(a47*a38);
  a38=(a02*a38);
  a55=(a38/a34);
  a36=(a36+a36);
  a36=(a31*a36);
  a55=(a55-a36);
  a55=(a48*a55);
  a39=(a39+a55);
  a39=(a39-a38);
  a39=(a23*a39);
  a38=(a50*a39);
  if (res[2]!=0) res[2][4]=a38;
  a55=(a23*a32);
  a36=(a55+a55);
  a36=(a06*a36);
  a56=(a48*a55);
  a56=(a56/a34);
  a55=(a56-a55);
  a55=(a47*a55);
  a55=(a02*a55);
  a57=(a55/a34);
  a56=(a56+a56);
  a56=(a31*a56);
  a57=(a57-a56);
  a57=(a48*a57);
  a36=(a36+a57);
  a36=(a36-a55);
  a36=(a23*a36);
  a55=(a50*a36);
  if (res[2]!=0) res[2][5]=a55;
  a57=(a49*a50);
  a56=(a57+a57);
  a56=(a06*a56);
  a58=(a48*a57);
  a58=(a58/a34);
  a57=(a58-a57);
  a57=(a47*a57);
  a57=(a02*a57);
  a59=(a57/a34);
  a58=(a58+a58);
  a58=(a31*a58);
  a59=(a59-a58);
  a59=(a48*a59);
  a56=(a56+a59);
  a56=(a56-a57);
  a57=(a23*a56);
  a59=(a50*a57);
  if (res[2]!=0) res[2][6]=a59;
  a58=(a49*a51);
  a60=(a58+a58);
  a60=(a06*a60);
  a61=(a48*a58);
  a61=(a61/a34);
  a58=(a61-a58);
  a58=(a47*a58);
  a58=(a02*a58);
  a62=(a58/a34);
  a61=(a61+a61);
  a61=(a31*a61);
  a62=(a62-a61);
  a62=(a48*a62);
  a60=(a60+a62);
  a60=(a60-a58);
  a58=(a23*a60);
  a62=(a50*a58);
  if (res[2]!=0) res[2][7]=a62;
  a61=(a49*a26);
  a63=(a61+a61);
  a63=(a06*a63);
  a64=(a48*a61);
  a64=(a64/a34);
  a61=(a64-a61);
  a61=(a47*a61);
  a61=(a02*a61);
  a65=(a61/a34);
  a64=(a64+a64);
  a64=(a31*a64);
  a65=(a65-a64);
  a65=(a48*a65);
  a63=(a63+a65);
  a63=(a63-a61);
  a61=(a23*a63);
  a65=(a50*a61);
  if (res[2]!=0) res[2][8]=a65;
  a64=(a49*a28);
  a66=(a64+a64);
  a66=(a06*a66);
  a67=(a48*a64);
  a67=(a67/a34);
  a64=(a67-a64);
  a64=(a47*a64);
  a64=(a02*a64);
  a68=(a64/a34);
  a67=(a67+a67);
  a67=(a31*a67);
  a68=(a68-a67);
  a68=(a48*a68);
  a66=(a66+a68);
  a66=(a66-a64);
  a64=(a23*a66);
  a68=(a50*a64);
  if (res[2]!=0) res[2][9]=a68;
  a67=(a49*a30);
  a69=(a67+a67);
  a69=(a06*a69);
  a70=(a48*a67);
  a70=(a70/a34);
  a67=(a70-a67);
  a67=(a47*a67);
  a67=(a02*a67);
  a71=(a67/a34);
  a70=(a70+a70);
  a70=(a31*a70);
  a71=(a71-a70);
  a71=(a48*a71);
  a69=(a69+a71);
  a69=(a69-a67);
  a67=(a23*a69);
  a71=(a50*a67);
  if (res[2]!=0) res[2][10]=a71;
  a70=(a49*a32);
  a72=(a70+a70);
  a06=(a06*a72);
  a72=(a48*a70);
  a72=(a72/a34);
  a70=(a72-a70);
  a70=(a47*a70);
  a70=(a02*a70);
  a34=(a70/a34);
  a72=(a72+a72);
  a31=(a31*a72);
  a34=(a34-a31);
  a48=(a48*a34);
  a06=(a06+a48);
  a06=(a06-a70);
  a23=(a23*a06);
  a70=(a50*a23);
  if (res[2]!=0) res[2][11]=a70;
  if (res[2]!=0) res[2][12]=a35;
  a33=(a51*a33);
  a33=(a33+a25);
  if (res[2]!=0) res[2][13]=a33;
  a33=(a51*a46);
  if (res[2]!=0) res[2][14]=a33;
  a35=(a51*a27);
  if (res[2]!=0) res[2][15]=a35;
  a48=(a51*a39);
  if (res[2]!=0) res[2][16]=a48;
  a34=(a51*a36);
  if (res[2]!=0) res[2][17]=a34;
  a31=(a51*a57);
  if (res[2]!=0) res[2][18]=a31;
  a72=(a51*a58);
  if (res[2]!=0) res[2][19]=a72;
  a73=(a51*a61);
  if (res[2]!=0) res[2][20]=a73;
  a74=(a51*a64);
  if (res[2]!=0) res[2][21]=a74;
  a75=(a51*a67);
  if (res[2]!=0) res[2][22]=a75;
  a76=(a51*a23);
  if (res[2]!=0) res[2][23]=a76;
  if (res[2]!=0) res[2][24]=a29;
  if (res[2]!=0) res[2][25]=a33;
  a46=(a26*a46);
  a46=(a46+a25);
  if (res[2]!=0) res[2][26]=a46;
  a46=(a26*a27);
  if (res[2]!=0) res[2][27]=a46;
  a33=(a26*a39);
  if (res[2]!=0) res[2][28]=a33;
  a29=(a26*a36);
  if (res[2]!=0) res[2][29]=a29;
  a77=(a26*a57);
  if (res[2]!=0) res[2][30]=a77;
  a78=(a26*a58);
  if (res[2]!=0) res[2][31]=a78;
  a79=(a26*a61);
  if (res[2]!=0) res[2][32]=a79;
  a80=(a26*a64);
  if (res[2]!=0) res[2][33]=a80;
  a81=(a26*a67);
  if (res[2]!=0) res[2][34]=a81;
  a82=(a26*a23);
  if (res[2]!=0) res[2][35]=a82;
  if (res[2]!=0) res[2][36]=a24;
  if (res[2]!=0) res[2][37]=a35;
  if (res[2]!=0) res[2][38]=a46;
  a27=(a28*a27);
  a27=(a27+a25);
  if (res[2]!=0) res[2][39]=a27;
  a27=(a28*a39);
  if (res[2]!=0) res[2][40]=a27;
  a46=(a28*a36);
  if (res[2]!=0) res[2][41]=a46;
  a35=(a28*a57);
  if (res[2]!=0) res[2][42]=a35;
  a24=(a28*a58);
  if (res[2]!=0) res[2][43]=a24;
  a83=(a28*a61);
  if (res[2]!=0) res[2][44]=a83;
  a84=(a28*a64);
  if (res[2]!=0) res[2][45]=a84;
  a85=(a28*a67);
  if (res[2]!=0) res[2][46]=a85;
  a86=(a28*a23);
  if (res[2]!=0) res[2][47]=a86;
  if (res[2]!=0) res[2][48]=a38;
  if (res[2]!=0) res[2][49]=a48;
  if (res[2]!=0) res[2][50]=a33;
  if (res[2]!=0) res[2][51]=a27;
  a39=(a30*a39);
  a39=(a39+a25);
  if (res[2]!=0) res[2][52]=a39;
  a39=(a30*a36);
  if (res[2]!=0) res[2][53]=a39;
  a27=(a30*a57);
  if (res[2]!=0) res[2][54]=a27;
  a33=(a30*a58);
  if (res[2]!=0) res[2][55]=a33;
  a48=(a30*a61);
  if (res[2]!=0) res[2][56]=a48;
  a38=(a30*a64);
  if (res[2]!=0) res[2][57]=a38;
  a87=(a30*a67);
  if (res[2]!=0) res[2][58]=a87;
  a88=(a30*a23);
  if (res[2]!=0) res[2][59]=a88;
  if (res[2]!=0) res[2][60]=a55;
  if (res[2]!=0) res[2][61]=a34;
  if (res[2]!=0) res[2][62]=a29;
  if (res[2]!=0) res[2][63]=a46;
  if (res[2]!=0) res[2][64]=a39;
  a36=(a32*a36);
  a36=(a36+a25);
  if (res[2]!=0) res[2][65]=a36;
  a57=(a32*a57);
  if (res[2]!=0) res[2][66]=a57;
  a58=(a32*a58);
  if (res[2]!=0) res[2][67]=a58;
  a61=(a32*a61);
  if (res[2]!=0) res[2][68]=a61;
  a64=(a32*a64);
  if (res[2]!=0) res[2][69]=a64;
  a67=(a32*a67);
  if (res[2]!=0) res[2][70]=a67;
  a23=(a32*a23);
  if (res[2]!=0) res[2][71]=a23;
  a47=(a53*a47);
  if (res[2]!=0) res[2][72]=a47;
  a47=(a43*a44);
  a47=(a47/a03);
  a36=(a44+a47);
  a36=(a37*a36);
  a36=(a02*a36);
  a25=(a44+a44);
  a25=(a52*a25);
  a39=(a36/a03);
  a46=(a52/a03);
  a47=(a47+a47);
  a47=(a46*a47);
  a39=(a39-a47);
  a39=(a43*a39);
  a25=(a25+a39);
  a36=(a36+a25);
  a36=(a44*a36);
  a25=(a02*a04);
  a25=(a01*a25);
  a04=(a04*a25);
  a05=(a02*a05);
  a00=(a00*a05);
  a04=(a04-a00);
  a04=(a02*a04);
  a36=(a36+a04);
  a36=(a36+a04);
  if (res[2]!=0) res[2][73]=a36;
  a36=(a43*a45);
  a36=(a36/a03);
  a04=(a45+a36);
  a04=(a37*a04);
  a04=(a02*a04);
  a00=(a45+a45);
  a00=(a52*a00);
  a05=(a04/a03);
  a36=(a36+a36);
  a36=(a46*a36);
  a05=(a05-a36);
  a05=(a43*a05);
  a00=(a00+a05);
  a04=(a04+a00);
  a00=(a44*a04);
  if (res[2]!=0) res[2][74]=a00;
  a05=(a43*a07);
  a05=(a05/a03);
  a36=(a07+a05);
  a36=(a37*a36);
  a36=(a02*a36);
  a25=(a07+a07);
  a25=(a52*a25);
  a39=(a36/a03);
  a05=(a05+a05);
  a05=(a46*a05);
  a39=(a39-a05);
  a39=(a43*a39);
  a25=(a25+a39);
  a36=(a36+a25);
  a25=(a44*a36);
  if (res[2]!=0) res[2][75]=a25;
  a39=(a43*a10);
  a39=(a39/a03);
  a05=(a10+a39);
  a05=(a37*a05);
  a05=(a02*a05);
  a47=(a10+a10);
  a47=(a52*a47);
  a29=(a05/a03);
  a39=(a39+a39);
  a39=(a46*a39);
  a29=(a29-a39);
  a29=(a43*a29);
  a47=(a47+a29);
  a05=(a05+a47);
  a47=(a44*a05);
  if (res[2]!=0) res[2][76]=a47;
  a29=(a43*a13);
  a29=(a29/a03);
  a39=(a13+a29);
  a39=(a37*a39);
  a39=(a02*a39);
  a34=(a13+a13);
  a34=(a52*a34);
  a55=(a39/a03);
  a29=(a29+a29);
  a29=(a46*a29);
  a55=(a55-a29);
  a55=(a43*a55);
  a34=(a34+a55);
  a39=(a39+a34);
  a34=(a44*a39);
  if (res[2]!=0) res[2][77]=a34;
  a55=(a43*a16);
  a55=(a55/a03);
  a29=(a16+a55);
  a37=(a37*a29);
  a37=(a02*a37);
  a29=(a16+a16);
  a52=(a52*a29);
  a03=(a37/a03);
  a55=(a55+a55);
  a46=(a46*a55);
  a03=(a03-a46);
  a43=(a43*a03);
  a52=(a52+a43);
  a37=(a37+a52);
  a44=(a44*a37);
  if (res[2]!=0) res[2][78]=a44;
  if (res[2]!=0) res[2][79]=a00;
  a04=(a45*a04);
  a00=(a02*a08);
  a00=(a01*a00);
  a08=(a08*a00);
  a09=(a02*a09);
  a42=(a42*a09);
  a08=(a08-a42);
  a08=(a02*a08);
  a04=(a04+a08);
  a04=(a04+a08);
  if (res[2]!=0) res[2][80]=a04;
  a04=(a45*a36);
  if (res[2]!=0) res[2][81]=a04;
  a08=(a45*a05);
  if (res[2]!=0) res[2][82]=a08;
  a42=(a45*a39);
  if (res[2]!=0) res[2][83]=a42;
  a45=(a45*a37);
  if (res[2]!=0) res[2][84]=a45;
  if (res[2]!=0) res[2][85]=a25;
  if (res[2]!=0) res[2][86]=a04;
  a36=(a07*a36);
  a04=(a02*a11);
  a04=(a01*a04);
  a11=(a11*a04);
  a12=(a02*a12);
  a54=(a54*a12);
  a11=(a11-a54);
  a11=(a02*a11);
  a36=(a36+a11);
  a36=(a36+a11);
  if (res[2]!=0) res[2][87]=a36;
  a36=(a07*a05);
  if (res[2]!=0) res[2][88]=a36;
  a11=(a07*a39);
  if (res[2]!=0) res[2][89]=a11;
  a07=(a07*a37);
  if (res[2]!=0) res[2][90]=a07;
  if (res[2]!=0) res[2][91]=a47;
  if (res[2]!=0) res[2][92]=a08;
  if (res[2]!=0) res[2][93]=a36;
  a05=(a10*a05);
  a36=(a02*a14);
  a36=(a01*a36);
  a14=(a14*a36);
  a15=(a02*a15);
  a41=(a41*a15);
  a14=(a14-a41);
  a14=(a02*a14);
  a05=(a05+a14);
  a05=(a05+a14);
  if (res[2]!=0) res[2][94]=a05;
  a05=(a10*a39);
  if (res[2]!=0) res[2][95]=a05;
  a10=(a10*a37);
  if (res[2]!=0) res[2][96]=a10;
  if (res[2]!=0) res[2][97]=a34;
  if (res[2]!=0) res[2][98]=a42;
  if (res[2]!=0) res[2][99]=a11;
  if (res[2]!=0) res[2][100]=a05;
  a39=(a13*a39);
  a05=(a02*a17);
  a05=(a01*a05);
  a17=(a17*a05);
  a18=(a02*a18);
  a40=(a40*a18);
  a17=(a17-a40);
  a17=(a02*a17);
  a39=(a39+a17);
  a39=(a39+a17);
  if (res[2]!=0) res[2][101]=a39;
  a13=(a13*a37);
  if (res[2]!=0) res[2][102]=a13;
  if (res[2]!=0) res[2][103]=a44;
  if (res[2]!=0) res[2][104]=a45;
  if (res[2]!=0) res[2][105]=a07;
  if (res[2]!=0) res[2][106]=a10;
  if (res[2]!=0) res[2][107]=a13;
  a16=(a16*a37);
  a37=(a02*a20);
  a01=(a01*a37);
  a20=(a20*a01);
  a21=(a02*a21);
  a19=(a19*a21);
  a20=(a20-a19);
  a02=(a02*a20);
  a16=(a16+a02);
  a16=(a16+a02);
  if (res[2]!=0) res[2][108]=a16;
  if (res[2]!=0) res[2][109]=a59;
  if (res[2]!=0) res[2][110]=a31;
  if (res[2]!=0) res[2][111]=a77;
  if (res[2]!=0) res[2][112]=a35;
  if (res[2]!=0) res[2][113]=a27;
  if (res[2]!=0) res[2][114]=a57;
  a56=(a49*a56);
  a56=(a50*a56);
  a53=(a53*a22);
  a56=(a56+a53);
  if (res[2]!=0) res[2][115]=a56;
  a60=(a49*a60);
  a56=(a50*a60);
  if (res[2]!=0) res[2][116]=a56;
  a63=(a49*a63);
  a22=(a50*a63);
  if (res[2]!=0) res[2][117]=a22;
  a66=(a49*a66);
  a57=(a50*a66);
  if (res[2]!=0) res[2][118]=a57;
  a69=(a49*a69);
  a27=(a50*a69);
  if (res[2]!=0) res[2][119]=a27;
  a49=(a49*a06);
  a50=(a50*a49);
  if (res[2]!=0) res[2][120]=a50;
  if (res[2]!=0) res[2][121]=a62;
  if (res[2]!=0) res[2][122]=a72;
  if (res[2]!=0) res[2][123]=a78;
  if (res[2]!=0) res[2][124]=a24;
  if (res[2]!=0) res[2][125]=a33;
  if (res[2]!=0) res[2][126]=a58;
  if (res[2]!=0) res[2][127]=a56;
  a60=(a51*a60);
  a60=(a60+a53);
  if (res[2]!=0) res[2][128]=a60;
  a60=(a51*a63);
  if (res[2]!=0) res[2][129]=a60;
  a56=(a51*a66);
  if (res[2]!=0) res[2][130]=a56;
  a58=(a51*a69);
  if (res[2]!=0) res[2][131]=a58;
  a51=(a51*a49);
  if (res[2]!=0) res[2][132]=a51;
  if (res[2]!=0) res[2][133]=a65;
  if (res[2]!=0) res[2][134]=a73;
  if (res[2]!=0) res[2][135]=a79;
  if (res[2]!=0) res[2][136]=a83;
  if (res[2]!=0) res[2][137]=a48;
  if (res[2]!=0) res[2][138]=a61;
  if (res[2]!=0) res[2][139]=a22;
  if (res[2]!=0) res[2][140]=a60;
  a63=(a26*a63);
  a63=(a63+a53);
  if (res[2]!=0) res[2][141]=a63;
  a63=(a26*a66);
  if (res[2]!=0) res[2][142]=a63;
  a60=(a26*a69);
  if (res[2]!=0) res[2][143]=a60;
  a26=(a26*a49);
  if (res[2]!=0) res[2][144]=a26;
  if (res[2]!=0) res[2][145]=a68;
  if (res[2]!=0) res[2][146]=a74;
  if (res[2]!=0) res[2][147]=a80;
  if (res[2]!=0) res[2][148]=a84;
  if (res[2]!=0) res[2][149]=a38;
  if (res[2]!=0) res[2][150]=a64;
  if (res[2]!=0) res[2][151]=a57;
  if (res[2]!=0) res[2][152]=a56;
  if (res[2]!=0) res[2][153]=a63;
  a66=(a28*a66);
  a66=(a66+a53);
  if (res[2]!=0) res[2][154]=a66;
  a66=(a28*a69);
  if (res[2]!=0) res[2][155]=a66;
  a28=(a28*a49);
  if (res[2]!=0) res[2][156]=a28;
  if (res[2]!=0) res[2][157]=a71;
  if (res[2]!=0) res[2][158]=a75;
  if (res[2]!=0) res[2][159]=a81;
  if (res[2]!=0) res[2][160]=a85;
  if (res[2]!=0) res[2][161]=a87;
  if (res[2]!=0) res[2][162]=a67;
  if (res[2]!=0) res[2][163]=a27;
  if (res[2]!=0) res[2][164]=a58;
  if (res[2]!=0) res[2][165]=a60;
  if (res[2]!=0) res[2][166]=a66;
  a69=(a30*a69);
  a69=(a69+a53);
  if (res[2]!=0) res[2][167]=a69;
  a30=(a30*a49);
  if (res[2]!=0) res[2][168]=a30;
  if (res[2]!=0) res[2][169]=a70;
  if (res[2]!=0) res[2][170]=a76;
  if (res[2]!=0) res[2][171]=a82;
  if (res[2]!=0) res[2][172]=a86;
  if (res[2]!=0) res[2][173]=a88;
  if (res[2]!=0) res[2][174]=a23;
  if (res[2]!=0) res[2][175]=a50;
  if (res[2]!=0) res[2][176]=a51;
  if (res[2]!=0) res[2][177]=a26;
  if (res[2]!=0) res[2][178]=a28;
  if (res[2]!=0) res[2][179]=a30;
  a32=(a32*a49);
  a32=(a32+a53);
  if (res[2]!=0) res[2][180]=a32;
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void s622arm_nmpc_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void s622arm_nmpc_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void s622arm_nmpc_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void s622arm_nmpc_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int s622arm_nmpc_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int s622arm_nmpc_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real s622arm_nmpc_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* s622arm_nmpc_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* s622arm_nmpc_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* s622arm_nmpc_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* s622arm_nmpc_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
