/**:
  ros__parameters:
    model_path: /home/robot/S622_robotarm/yolo-obb3.pt
    device: auto
    conf: 0.55
    imgsz: 640
    enable_visualization: true
    enable_ema_smoothing: true
    ema_alpha: 0.35
    sync_slop: 0.03

