/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) s622arm_nmpc_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {33, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {19, 1, 1};

/* s622arm_nmpc_cost_ext_cost_fun_jac:(i0[12],i1[7],i2[0],i3[33])->(o0,o1[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53;
  a00=arg[3]? arg[3][12] : 0;
  a01=4.;
  a02=5.0000000000000000e-01;
  a03=arg[0]? arg[0][0] : 0;
  a04=arg[3]? arg[3][0] : 0;
  a03=(a03-a04);
  a04=(a02*a03);
  a05=sin(a04);
  a06=casadi_sq(a05);
  a07=arg[0]? arg[0][1] : 0;
  a08=arg[3]? arg[3][1] : 0;
  a07=(a07-a08);
  a08=(a02*a07);
  a09=sin(a08);
  a10=casadi_sq(a09);
  a06=(a06+a10);
  a10=arg[0]? arg[0][2] : 0;
  a11=arg[3]? arg[3][2] : 0;
  a10=(a10-a11);
  a11=(a02*a10);
  a12=sin(a11);
  a13=casadi_sq(a12);
  a06=(a06+a13);
  a13=arg[0]? arg[0][3] : 0;
  a14=arg[3]? arg[3][3] : 0;
  a13=(a13-a14);
  a14=(a02*a13);
  a15=sin(a14);
  a16=casadi_sq(a15);
  a06=(a06+a16);
  a16=arg[0]? arg[0][4] : 0;
  a17=arg[3]? arg[3][4] : 0;
  a16=(a16-a17);
  a17=(a02*a16);
  a18=sin(a17);
  a19=casadi_sq(a18);
  a06=(a06+a19);
  a19=arg[0]? arg[0][5] : 0;
  a20=arg[3]? arg[3][5] : 0;
  a19=(a19-a20);
  a20=(a02*a19);
  a21=sin(a20);
  a22=casadi_sq(a21);
  a06=(a06+a22);
  a06=(a01*a06);
  a06=(a00*a06);
  a22=arg[3]? arg[3][13] : 0;
  a23=arg[0]? arg[0][6] : 0;
  a24=arg[3]? arg[3][6] : 0;
  a24=(a23-a24);
  a25=casadi_sq(a24);
  a26=arg[0]? arg[0][7] : 0;
  a27=arg[3]? arg[3][7] : 0;
  a27=(a26-a27);
  a28=casadi_sq(a27);
  a25=(a25+a28);
  a28=arg[0]? arg[0][8] : 0;
  a29=arg[3]? arg[3][8] : 0;
  a29=(a28-a29);
  a30=casadi_sq(a29);
  a25=(a25+a30);
  a30=arg[0]? arg[0][9] : 0;
  a31=arg[3]? arg[3][9] : 0;
  a31=(a30-a31);
  a32=casadi_sq(a31);
  a25=(a25+a32);
  a32=arg[0]? arg[0][10] : 0;
  a33=arg[3]? arg[3][10] : 0;
  a33=(a32-a33);
  a34=casadi_sq(a33);
  a25=(a25+a34);
  a34=arg[0]? arg[0][11] : 0;
  a35=arg[3]? arg[3][11] : 0;
  a35=(a34-a35);
  a36=casadi_sq(a35);
  a25=(a25+a36);
  a25=(a22*a25);
  a06=(a06+a25);
  a25=arg[3]? arg[3][14] : 0;
  a36=arg[1]? arg[1][0] : 0;
  a37=casadi_sq(a36);
  a38=arg[1]? arg[1][1] : 0;
  a39=casadi_sq(a38);
  a37=(a37+a39);
  a39=arg[1]? arg[1][2] : 0;
  a40=casadi_sq(a39);
  a37=(a37+a40);
  a40=arg[1]? arg[1][3] : 0;
  a41=casadi_sq(a40);
  a37=(a37+a41);
  a41=arg[1]? arg[1][4] : 0;
  a42=casadi_sq(a41);
  a37=(a37+a42);
  a42=arg[1]? arg[1][5] : 0;
  a43=casadi_sq(a42);
  a37=(a37+a43);
  a37=(a25*a37);
  a06=(a06+a37);
  a37=arg[3]? arg[3][22] : 0;
  a43=arg[3]? arg[3][21] : 0;
  a44=arg[3]? arg[3][15] : 0;
  a03=(a44*a03);
  a45=arg[3]? arg[3][16] : 0;
  a07=(a45*a07);
  a03=(a03+a07);
  a07=arg[3]? arg[3][17] : 0;
  a10=(a07*a10);
  a03=(a03+a10);
  a10=arg[3]? arg[3][18] : 0;
  a13=(a10*a13);
  a03=(a03+a13);
  a13=arg[3]? arg[3][19] : 0;
  a16=(a13*a16);
  a03=(a03+a16);
  a16=arg[3]? arg[3][20] : 0;
  a19=(a16*a19);
  a03=(a03+a19);
  a43=(a43+a03);
  a03=casadi_sq(a43);
  a19=9.9999999999999995e-07;
  a03=(a03+a19);
  a03=sqrt(a03);
  a46=(a43+a03);
  a47=(a02*a46);
  a47=casadi_sq(a47);
  a47=(a37*a47);
  a06=(a06+a47);
  a47=arg[3]? arg[3][31] : 0;
  a48=arg[3]? arg[3][29] : 0;
  a49=2.0000000000000000e-02;
  a50=arg[3]? arg[3][23] : 0;
  a23=(a50*a23);
  a51=arg[3]? arg[3][24] : 0;
  a26=(a51*a26);
  a23=(a23+a26);
  a26=arg[3]? arg[3][25] : 0;
  a28=(a26*a28);
  a23=(a23+a28);
  a28=arg[3]? arg[3][26] : 0;
  a30=(a28*a30);
  a23=(a23+a30);
  a30=arg[3]? arg[3][27] : 0;
  a32=(a30*a32);
  a23=(a23+a32);
  a32=arg[3]? arg[3][28] : 0;
  a34=(a32*a34);
  a23=(a23+a34);
  a34=arg[3]? arg[3][30] : 0;
  a23=(a23+a34);
  a23=(a49*a23);
  a48=(a48+a23);
  a23=2.0000000000000001e-04;
  a34=(a50*a36);
  a52=(a51*a38);
  a34=(a34+a52);
  a52=(a26*a39);
  a34=(a34+a52);
  a52=(a28*a40);
  a34=(a34+a52);
  a52=(a30*a41);
  a34=(a34+a52);
  a52=(a32*a42);
  a34=(a34+a52);
  a34=(a23*a34);
  a48=(a48+a34);
  a34=casadi_sq(a48);
  a34=(a34+a19);
  a34=sqrt(a34);
  a19=(a34-a48);
  a52=(a02*a19);
  a52=casadi_sq(a52);
  a52=(a47*a52);
  a06=(a06+a52);
  a52=arg[1]? arg[1][6] : 0;
  a53=casadi_sq(a52);
  a53=(a47*a53);
  a06=(a06+a53);
  if (res[0]!=0) res[0][0]=a06;
  a48=(a48+a48);
  a19=(a19*a47);
  a19=(a02*a19);
  a34=(a34+a34);
  a34=(a19/a34);
  a48=(a48*a34);
  a48=(a48-a19);
  a23=(a23*a48);
  a19=(a50*a23);
  a36=(a36+a36);
  a36=(a36*a25);
  a19=(a19+a36);
  if (res[1]!=0) res[1][0]=a19;
  a19=(a51*a23);
  a38=(a38+a38);
  a38=(a38*a25);
  a19=(a19+a38);
  if (res[1]!=0) res[1][1]=a19;
  a19=(a26*a23);
  a39=(a39+a39);
  a39=(a39*a25);
  a19=(a19+a39);
  if (res[1]!=0) res[1][2]=a19;
  a19=(a28*a23);
  a40=(a40+a40);
  a40=(a40*a25);
  a19=(a19+a40);
  if (res[1]!=0) res[1][3]=a19;
  a19=(a30*a23);
  a41=(a41+a41);
  a41=(a41*a25);
  a19=(a19+a41);
  if (res[1]!=0) res[1][4]=a19;
  a23=(a32*a23);
  a42=(a42+a42);
  a42=(a42*a25);
  a23=(a23+a42);
  if (res[1]!=0) res[1][5]=a23;
  a52=(a52+a52);
  a52=(a52*a47);
  if (res[1]!=0) res[1][6]=a52;
  a46=(a46*a37);
  a46=(a02*a46);
  a43=(a43+a43);
  a03=(a03+a03);
  a03=(a46/a03);
  a43=(a43*a03);
  a46=(a46+a43);
  a44=(a44*a46);
  a04=cos(a04);
  a01=(a01*a00);
  a05=(a05*a01);
  a04=(a04*a05);
  a04=(a02*a04);
  a44=(a44+a04);
  a44=(a44+a04);
  if (res[1]!=0) res[1][7]=a44;
  a45=(a45*a46);
  a08=cos(a08);
  a09=(a09*a01);
  a08=(a08*a09);
  a08=(a02*a08);
  a45=(a45+a08);
  a45=(a45+a08);
  if (res[1]!=0) res[1][8]=a45;
  a07=(a07*a46);
  a11=cos(a11);
  a12=(a12*a01);
  a11=(a11*a12);
  a11=(a02*a11);
  a07=(a07+a11);
  a07=(a07+a11);
  if (res[1]!=0) res[1][9]=a07;
  a10=(a10*a46);
  a14=cos(a14);
  a15=(a15*a01);
  a14=(a14*a15);
  a14=(a02*a14);
  a10=(a10+a14);
  a10=(a10+a14);
  if (res[1]!=0) res[1][10]=a10;
  a13=(a13*a46);
  a17=cos(a17);
  a18=(a18*a01);
  a17=(a17*a18);
  a17=(a02*a17);
  a13=(a13+a17);
  a13=(a13+a17);
  if (res[1]!=0) res[1][11]=a13;
  a16=(a16*a46);
  a20=cos(a20);
  a21=(a21*a01);
  a20=(a20*a21);
  a02=(a02*a20);
  a16=(a16+a02);
  a16=(a16+a02);
  if (res[1]!=0) res[1][12]=a16;
  a49=(a49*a48);
  a50=(a50*a49);
  a24=(a24+a24);
  a24=(a24*a22);
  a50=(a50+a24);
  if (res[1]!=0) res[1][13]=a50;
  a51=(a51*a49);
  a27=(a27+a27);
  a27=(a27*a22);
  a51=(a51+a27);
  if (res[1]!=0) res[1][14]=a51;
  a26=(a26*a49);
  a29=(a29+a29);
  a29=(a29*a22);
  a26=(a26+a29);
  if (res[1]!=0) res[1][15]=a26;
  a28=(a28*a49);
  a31=(a31+a31);
  a31=(a31*a22);
  a28=(a28+a31);
  if (res[1]!=0) res[1][16]=a28;
  a30=(a30*a49);
  a33=(a33+a33);
  a33=(a33*a22);
  a30=(a30+a33);
  if (res[1]!=0) res[1][17]=a30;
  a32=(a32*a49);
  a35=(a35+a35);
  a35=(a35*a22);
  a32=(a32+a35);
  if (res[1]!=0) res[1][18]=a32;
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void s622arm_nmpc_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void s622arm_nmpc_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void s622arm_nmpc_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void s622arm_nmpc_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int s622arm_nmpc_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int s622arm_nmpc_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real s622arm_nmpc_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* s622arm_nmpc_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* s622arm_nmpc_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* s622arm_nmpc_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* s622arm_nmpc_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_nmpc_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
