/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) s622arm_mpc_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {33, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {19, 1, 1};

/* s622arm_mpc_cost_ext_cost_0_fun_jac:(i0[12],i1[7],i2[0],i3[33])->(o0,o1[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32;
  a00=arg[3]? arg[3][12] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a02=arg[3]? arg[3][0] : 0;
  a01=(a01-a02);
  a02=casadi_sq(a01);
  a03=arg[0]? arg[0][1] : 0;
  a04=arg[3]? arg[3][1] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a02=(a02+a04);
  a04=arg[0]? arg[0][2] : 0;
  a05=arg[3]? arg[3][2] : 0;
  a04=(a04-a05);
  a05=casadi_sq(a04);
  a02=(a02+a05);
  a05=arg[0]? arg[0][3] : 0;
  a06=arg[3]? arg[3][3] : 0;
  a05=(a05-a06);
  a06=casadi_sq(a05);
  a02=(a02+a06);
  a06=arg[0]? arg[0][4] : 0;
  a07=arg[3]? arg[3][4] : 0;
  a06=(a06-a07);
  a07=casadi_sq(a06);
  a02=(a02+a07);
  a07=arg[0]? arg[0][5] : 0;
  a08=arg[3]? arg[3][5] : 0;
  a07=(a07-a08);
  a08=casadi_sq(a07);
  a02=(a02+a08);
  a08=(a00*a02);
  a09=arg[3]? arg[3][13] : 0;
  a10=arg[0]? arg[0][6] : 0;
  a11=arg[3]? arg[3][6] : 0;
  a10=(a10-a11);
  a11=casadi_sq(a10);
  a12=arg[0]? arg[0][7] : 0;
  a13=arg[3]? arg[3][7] : 0;
  a12=(a12-a13);
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a13=arg[0]? arg[0][8] : 0;
  a14=arg[3]? arg[3][8] : 0;
  a13=(a13-a14);
  a14=casadi_sq(a13);
  a11=(a11+a14);
  a14=arg[0]? arg[0][9] : 0;
  a15=arg[3]? arg[3][9] : 0;
  a14=(a14-a15);
  a15=casadi_sq(a14);
  a11=(a11+a15);
  a15=arg[0]? arg[0][10] : 0;
  a16=arg[3]? arg[3][10] : 0;
  a15=(a15-a16);
  a16=casadi_sq(a15);
  a11=(a11+a16);
  a16=arg[0]? arg[0][11] : 0;
  a17=arg[3]? arg[3][11] : 0;
  a16=(a16-a17);
  a17=casadi_sq(a16);
  a11=(a11+a17);
  a11=(a09*a11);
  a08=(a08+a11);
  a11=arg[3]? arg[3][14] : 0;
  a17=arg[1]? arg[1][0] : 0;
  a18=casadi_sq(a17);
  a19=arg[1]? arg[1][1] : 0;
  a20=casadi_sq(a19);
  a18=(a18+a20);
  a20=arg[1]? arg[1][2] : 0;
  a21=casadi_sq(a20);
  a18=(a18+a21);
  a21=arg[1]? arg[1][3] : 0;
  a22=casadi_sq(a21);
  a18=(a18+a22);
  a22=arg[1]? arg[1][4] : 0;
  a23=casadi_sq(a22);
  a18=(a18+a23);
  a23=arg[1]? arg[1][5] : 0;
  a24=casadi_sq(a23);
  a18=(a18+a24);
  a18=(a11*a18);
  a08=(a08+a18);
  a18=arg[3]? arg[3][22] : 0;
  a24=arg[3]? arg[3][15] : 0;
  a25=(a24*a01);
  a26=arg[3]? arg[3][16] : 0;
  a27=(a26*a03);
  a25=(a25+a27);
  a27=arg[3]? arg[3][17] : 0;
  a28=(a27*a04);
  a25=(a25+a28);
  a28=arg[3]? arg[3][18] : 0;
  a29=(a28*a05);
  a25=(a25+a29);
  a29=arg[3]? arg[3][19] : 0;
  a30=(a29*a06);
  a25=(a25+a30);
  a30=arg[3]? arg[3][20] : 0;
  a31=(a30*a07);
  a25=(a25+a31);
  a31=arg[3]? arg[3][21] : 0;
  a02=(a31*a02);
  a25=(a25+a02);
  a25=(a18*a25);
  a08=(a08+a25);
  a25=arg[3]? arg[3][31] : 0;
  a02=arg[1]? arg[1][6] : 0;
  a32=casadi_sq(a02);
  a32=(a25*a32);
  a08=(a08+a32);
  if (res[0]!=0) res[0][0]=a08;
  a17=(a17+a17);
  a17=(a17*a11);
  if (res[1]!=0) res[1][0]=a17;
  a19=(a19+a19);
  a19=(a19*a11);
  if (res[1]!=0) res[1][1]=a19;
  a20=(a20+a20);
  a20=(a20*a11);
  if (res[1]!=0) res[1][2]=a20;
  a21=(a21+a21);
  a21=(a21*a11);
  if (res[1]!=0) res[1][3]=a21;
  a22=(a22+a22);
  a22=(a22*a11);
  if (res[1]!=0) res[1][4]=a22;
  a23=(a23+a23);
  a23=(a23*a11);
  if (res[1]!=0) res[1][5]=a23;
  a02=(a02+a02);
  a02=(a02*a25);
  if (res[1]!=0) res[1][6]=a02;
  a01=(a01+a01);
  a31=(a31*a18);
  a02=(a01*a31);
  a24=(a24*a18);
  a02=(a02+a24);
  a01=(a01*a00);
  a02=(a02+a01);
  if (res[1]!=0) res[1][7]=a02;
  a03=(a03+a03);
  a02=(a03*a31);
  a26=(a26*a18);
  a02=(a02+a26);
  a03=(a03*a00);
  a02=(a02+a03);
  if (res[1]!=0) res[1][8]=a02;
  a04=(a04+a04);
  a02=(a04*a31);
  a27=(a27*a18);
  a02=(a02+a27);
  a04=(a04*a00);
  a02=(a02+a04);
  if (res[1]!=0) res[1][9]=a02;
  a05=(a05+a05);
  a02=(a05*a31);
  a28=(a28*a18);
  a02=(a02+a28);
  a05=(a05*a00);
  a02=(a02+a05);
  if (res[1]!=0) res[1][10]=a02;
  a06=(a06+a06);
  a02=(a06*a31);
  a29=(a29*a18);
  a02=(a02+a29);
  a06=(a06*a00);
  a02=(a02+a06);
  if (res[1]!=0) res[1][11]=a02;
  a07=(a07+a07);
  a31=(a07*a31);
  a30=(a30*a18);
  a31=(a31+a30);
  a07=(a07*a00);
  a31=(a31+a07);
  if (res[1]!=0) res[1][12]=a31;
  a10=(a10+a10);
  a10=(a10*a09);
  if (res[1]!=0) res[1][13]=a10;
  a12=(a12+a12);
  a12=(a12*a09);
  if (res[1]!=0) res[1][14]=a12;
  a13=(a13+a13);
  a13=(a13*a09);
  if (res[1]!=0) res[1][15]=a13;
  a14=(a14+a14);
  a14=(a14*a09);
  if (res[1]!=0) res[1][16]=a14;
  a15=(a15+a15);
  a15=(a15*a09);
  if (res[1]!=0) res[1][17]=a15;
  a16=(a16+a16);
  a16=(a16*a09);
  if (res[1]!=0) res[1][18]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_mpc_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int s622arm_mpc_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_mpc_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void s622arm_mpc_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int s622arm_mpc_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void s622arm_mpc_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void s622arm_mpc_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void s622arm_mpc_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int s622arm_mpc_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int s622arm_mpc_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real s622arm_mpc_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* s622arm_mpc_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* s622arm_mpc_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* s622arm_mpc_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* s622arm_mpc_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int s622arm_mpc_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int s622arm_mpc_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
