/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fairino_arm_nmpc_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {33, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

/* fairino_arm_nmpc_cost_ext_cost_e_fun_jac:(i0[12],i1[0],i2[0],i3[33])->(o0,o1[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  a00=arg[3]? arg[3][12] : 0;
  a01=4.;
  a02=5.0000000000000000e-01;
  a03=arg[0]? arg[0][0] : 0;
  a04=arg[3]? arg[3][0] : 0;
  a03=(a03-a04);
  a03=(a02*a03);
  a04=sin(a03);
  a05=casadi_sq(a04);
  a06=arg[0]? arg[0][1] : 0;
  a07=arg[3]? arg[3][1] : 0;
  a06=(a06-a07);
  a06=(a02*a06);
  a07=sin(a06);
  a08=casadi_sq(a07);
  a05=(a05+a08);
  a08=arg[0]? arg[0][2] : 0;
  a09=arg[3]? arg[3][2] : 0;
  a08=(a08-a09);
  a08=(a02*a08);
  a09=sin(a08);
  a10=casadi_sq(a09);
  a05=(a05+a10);
  a10=arg[0]? arg[0][3] : 0;
  a11=arg[3]? arg[3][3] : 0;
  a10=(a10-a11);
  a10=(a02*a10);
  a11=sin(a10);
  a12=casadi_sq(a11);
  a05=(a05+a12);
  a12=arg[0]? arg[0][4] : 0;
  a13=arg[3]? arg[3][4] : 0;
  a12=(a12-a13);
  a12=(a02*a12);
  a13=sin(a12);
  a14=casadi_sq(a13);
  a05=(a05+a14);
  a14=arg[0]? arg[0][5] : 0;
  a15=arg[3]? arg[3][5] : 0;
  a14=(a14-a15);
  a02=(a02*a14);
  a14=sin(a02);
  a15=casadi_sq(a14);
  a05=(a05+a15);
  a05=(a01*a05);
  a05=(a00*a05);
  a15=2.;
  a16=arg[3]? arg[3][13] : 0;
  a15=(a15*a16);
  a16=arg[0]? arg[0][6] : 0;
  a17=arg[3]? arg[3][6] : 0;
  a16=(a16-a17);
  a17=casadi_sq(a16);
  a18=arg[0]? arg[0][7] : 0;
  a19=arg[3]? arg[3][7] : 0;
  a18=(a18-a19);
  a19=casadi_sq(a18);
  a17=(a17+a19);
  a19=arg[0]? arg[0][8] : 0;
  a20=arg[3]? arg[3][8] : 0;
  a19=(a19-a20);
  a20=casadi_sq(a19);
  a17=(a17+a20);
  a20=arg[0]? arg[0][9] : 0;
  a21=arg[3]? arg[3][9] : 0;
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a17=(a17+a21);
  a21=arg[0]? arg[0][10] : 0;
  a22=arg[3]? arg[3][10] : 0;
  a21=(a21-a22);
  a22=casadi_sq(a21);
  a17=(a17+a22);
  a22=arg[0]? arg[0][11] : 0;
  a23=arg[3]? arg[3][11] : 0;
  a22=(a22-a23);
  a23=casadi_sq(a22);
  a17=(a17+a23);
  a17=(a15*a17);
  a05=(a05+a17);
  if (res[0]!=0) res[0][0]=a05;
  a03=cos(a03);
  a01=(a01*a00);
  a04=(a04*a01);
  a03=(a03*a04);
  if (res[1]!=0) res[1][0]=a03;
  a06=cos(a06);
  a07=(a07*a01);
  a06=(a06*a07);
  if (res[1]!=0) res[1][1]=a06;
  a08=cos(a08);
  a09=(a09*a01);
  a08=(a08*a09);
  if (res[1]!=0) res[1][2]=a08;
  a10=cos(a10);
  a11=(a11*a01);
  a10=(a10*a11);
  if (res[1]!=0) res[1][3]=a10;
  a12=cos(a12);
  a13=(a13*a01);
  a12=(a12*a13);
  if (res[1]!=0) res[1][4]=a12;
  a02=cos(a02);
  a14=(a14*a01);
  a02=(a02*a14);
  if (res[1]!=0) res[1][5]=a02;
  a16=(a16+a16);
  a16=(a16*a15);
  if (res[1]!=0) res[1][6]=a16;
  a18=(a18+a18);
  a18=(a18*a15);
  if (res[1]!=0) res[1][7]=a18;
  a19=(a19+a19);
  a19=(a19*a15);
  if (res[1]!=0) res[1][8]=a19;
  a20=(a20+a20);
  a20=(a20*a15);
  if (res[1]!=0) res[1][9]=a20;
  a21=(a21+a21);
  a21=(a21*a15);
  if (res[1]!=0) res[1][10]=a21;
  a22=(a22+a22);
  a22=(a22*a15);
  if (res[1]!=0) res[1][11]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int fairino_arm_nmpc_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fairino_arm_nmpc_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fairino_arm_nmpc_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fairino_arm_nmpc_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fairino_arm_nmpc_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fairino_arm_nmpc_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fairino_arm_nmpc_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void fairino_arm_nmpc_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fairino_arm_nmpc_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int fairino_arm_nmpc_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real fairino_arm_nmpc_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fairino_arm_nmpc_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fairino_arm_nmpc_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fairino_arm_nmpc_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fairino_arm_nmpc_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fairino_arm_nmpc_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fairino_arm_nmpc_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
