robot_name: s622
moveit_config_package: s622_moveit_config
moveit_config_name: s622
description_package: s622_moveit_descriptions
gazebo_xacro: config/robots/s622/s622_gazebo.urdf.xacro
semantic_file: config/s622_moveit_descriptions.srdf
default_kinematics_file: config/kinematics.yaml
kinematics_fairino_file: config/kinematics_fairino.yaml
kinematics_kdl_file: config/kinematics_kdl.yaml
planning_pipeline_file: config/fairino_planning.yaml
controllers_file: config/ros2_controllers.yaml
initial_positions_file: config/initial_positions.yaml
has_gripper: true
has_camera: true
spawn_name: robot_arm
spawn_xyz: [0.0, 0.0, 0.0]
spawn_rpy: [0.0, 0.0, 0.0]
arm_controller: /robot_arm_controller
hand_controller: /hand_controller
arm_joints: [j1, j2, j3, j4, j5, j6]
hand_joints: [finger1_joint, finger2_joint]
planning_pipelines: [fairino, ompl]
default_planning_pipeline: fairino
group_name: robot_arm
planning_frame: base_link
ee_frame_name: grasp_frame
servo_parameters_file: config/servo_parameters.yaml

